
#ifndef GEOGRAM_BASIC_VERSION
#define GEOGRAM_BASIC_VERSION

#define VORPALINE_VERSION_MAJOR "1"
#define VORPALINE_VERSION_MINOR "8"
#define VORPALINE_VERSION_PATCH "9"
#define VORPALINE_VERSION "1.8.9-rc"
#define VORPALINE_BUILD_NUMBER ""
#define VORPALINE_BUILD_DATE "2024-02-21 11:29:59"
#define VORPALINE_SVN_REVISION ""

#endif

